controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheels_controller:
      type: velocity_controllers/JointGroupVelocityController

    head_controller:
      type: position_controllers/JointGroupPositionController

wheels_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position

head_controller:
  ros__parameters:
    joints:
      - head_x_joint
      - head_y_joint
    command_interfaces:
      - position
    state_interfaces:
      - position