controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    head_controller:
          type: position_controllers/JointGroupPositionController

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_footprint
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3641
    wheel_radius: 0.069
    use_stamped_vel: false

head_controller:
  ros__parameters:
    joints:
      - head_x_joint
      - head_y_joint
    command_interfaces:
      - position
    state_interfaces:
      - position