head_stabilizer_node:
  ros__parameters:
    imu_topic: "/imu_base"
    command_topic: "/head_controller/commands"
    joint_names: ["head_x_joint", "head_y_joint"]

    # Joint limits
    limit_x: 0.349  # 20 degrees in radians
    limit_y: 0.349

    # PID gains
    Kp_x: 0.9
    Ki_x: 0.001
    Kd_x: 0.01
    Kp_y: 0.9
    Ki_y: 0.001
    Kd_y: 0.01

    # Integral windup protection
    integral_max_x: 0.02
    integral_max_y: 0.02